/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [{
        _id: "Wo5dMEP_BbI",
        title: "Nuvvani Idhi Needani Full Video Song || Maharshi Songs || MaheshBabu || VamshiPaidipally",
        description: "Watch & Enjoy #NuvvaniIdhiNeedani Full Video Song From #Maharshi Movie.",
        creator: "Aditya Music",
        thumbnail: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.N48gzpEKzCVEIpEI1JqW2wHaEK%26pid%3DApi&f=1&ipt=b3cee7a5fdb9925cce94251da371ab86397e93cfda3fe4b6bdc8b72f0f907ea7&ipo=images",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLReKISHylSA5PAVOXXnQycmveRc6NdoQT661kJswg=s48-c-k-c0x00ffffff-no-rj",
        views: "2C",
        duration: "4:00",
        categoryName: "Tollywood",
        src: "https://www.youtube.com/embed/4dbiE-da82E",
    },
    {
        _id: "F_Riqjdh2oM",
        title: "Choopultho - Radha | Sharwanand | Lavanya | Aksha",
        creator: "Junglee Music Telugu",
        description: "#Radha ft. Sharwanand & Lavnya Tripathi. Music composed by Radan and directed by Chandra Mohan. Movie is Produced by Bhogavalli Baapineedu.",
        thumbnail: "https://i.ytimg.com/vi/W_cNJEaW6jg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCnHaRc5KvmdDC_jWmHsKxwvLFRzQ",
        avatar: "https://yt3.googleusercontent.com/9V21v6ZBVBSxfK0LMK3YgLatb4JRnw01RUmMbaFikIxUsDfn7juW2DwTTtvPKC0XhFBdu_EUXw=s176-c-k-c0x00ffffff-no-rj",
        views: "18L",
        duration: "3:50",
        categoryName: "Tollywood",
        src: "https://www.youtube.com/embed/W_cNJEaW6jg",
    },
    {
        _id: "Q_Riqjdh2oM",
        title: "#PataasPilla Full Video Song | DJTillu | Siddhu, Neha Shetty ",
        creator: "Aditya Music",
        description: "Watch & Enjoy Pataas Pilla Full Video Song From The Movie #DJTillu. ",
        thumbnail: "https://i.ytimg.com/vi/VdGY5cs7onc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDIOC4aoW_PmOZh4HGA4Gsj3qQUzg",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLReKISHylSA5PAVOXXnQycmveRc6NdoQT661kJswg=s48-c-k-c0x00ffffff-no-rj",
        views: "1.1C",
        duration: "3:31",
        categoryName: "Tollywood",
        src: "https://www.youtube.com/embed/VdGY5cs7onc",
    },
    {
        _id: "A_Stqjdh2oM",
        title: "Channa Mereya (unplugged with Lyrics) : Arijit Singh |",
        creator: "Infinity Saga",
        description: "Watch & Enjoy Pataas Pilla Full Video Song From The Movie #DJTillu. ",
        thumbnail: "https://i.ytimg.com/vi/SQSR8-PftwA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB_fMlnkOAAzDIwaKNpvvlEMJc8vg",
        avatar: "https://yt3.ggpht.com/WkDJxNndzmmBIQJGV_elWu40bhk8ZOG21WRXxe3Cqam3SErDHZ2j0JwEPjFGrDng2O9U0CnXVw=s176-c-k-c0x00ffffff-no-rj",
        views: "27L",
        duration: "2:44",
        categoryName: "Bollywood",
        src: "https://www.youtube.com/embed/SQSR8-PftwA",
    },
    {
        _id: "V_Stdjah2ji",
        title: "Ranjha  Official Video | Shershaah | Sidharth Kiara ",
        creator: "Sony Music India",
        description: "When you've finally gotten to be with the love of your life, how do you say goodbye so soon?. ",
        thumbnail: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOVP.EkmMojnpO5XM6-mkZkL_xgHgFo%26pid%3DApi&f=1",
        avatar: "https://yt3.ggpht.com/cE8QOPMlZBkzDHCp-7F35Rtahl64oPrdKaKZ2AgAdBs0tiOw1e9SVAEaPsa6RVGmKRW8leV8=s176-c-k-c0x00ffffff-no-rj-mo",
        views: "25C",
        duration: "3:14",
        categoryName: "Bollywood",
        src: "https://www.youtube.com/embed/V7LwfY5U5WI",
    },
    {
        _id: "W_Stdjam5ji",
        title: "Pal Pal Dil Ke Paas - Title | Arijit Singh | Karan Deol, Sahher ",
        creator: "Zee Music Company",
        description: "When you've finally gotten to be with the love of your life, how do you say goodbye so soon?. ",
        thumbnail: "https://i.ytimg.com/vi/lgTHGZF3BQw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDP7mScJBXBlgFhXWQw9QMvQKxSHw",
        avatar: "https://yt3.ggpht.com/EEGERwlaKJd27zSEPQF3d__-tPyppIgFfKvNfBkWa7ssMKBWqQUbuCTLe-kAnTB1r6kJQVxyxwY=s176-c-k-c0x00ffffff-no-rj",
        views: "19C",
        duration: "3:03",
        categoryName: "Bollywood",
        src: "https://www.youtube.com/embed/lgTHGZF3BQw",
    },
    {
        _id: "N_Stdjkm5li",
        title: "Tom & Jerry | You're Still My Baby, Baby | Classic Cartoon | WB Kids",
        creator: "WB Kids",
        description: "Eager to impress Toodles, Tom smuggles a double bass into the courtyard below for a serenade!",
        thumbnail: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOVP.DRThkUYAL5YWTwnUZwZPNgHgFo%26pid%3DApi&f=1",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLTWSuXvajlpkF0dcqa8Mf2Va5svzH7b9EC1x0Q7zA=s48-c-k-c0x00ffffff-no-rj",
        views: "23L",
        duration: "3:17",
        categoryName: "Cartoon",
        src: "https://www.youtube.com/embed/PZcHR_zMRgU",
    },
    {
        _id: "D_Stdlmp9lm",
        title: "*NEW SONG!* I'M BEAN, MR. BEAN | Music Video | Mr. Bean Official",
        creator: "Mr Bean",
        description: "Welcome to the official Mr Bean Channel. Here you will find all of your favourite Mr Bean moments.",
        thumbnail: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.h4sQh9v2yarCffLuZ8_3bwHaEK%26pid%3DApi&f=1&ipt=673ad72534984a83a21e522f8101bb63416f1050ac38069173d64a13045f7881&ipo=images",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLSOkEcl2lDSFEBtGFoNL8eLULm1RkXnBcb3i45uxA=s48-c-k-c0x00ffffff-no-rj",
        views: "2.1C",
        duration: "2:16",
        categoryName: "Cartoon",
        src: "https://www.youtube.com/embed/AP4fxEnn4NM",
    }
];